intermediate of important update (not completed)

diff --git a/gsl/build_gsl b/gsl/build_gsl
--- a/gsl/build_gsl
+++ b/gsl/build_gsl
@@ -5,60 +5,88 @@
 esc=`echo -en "\033"`
 
 # Set colors
+#{{{
 cc_red="${esc}[0;31m"
 cc_green="${esc}[0;32m"
 cc_yellow="${esc}[0;33m"
 cc_blue="${esc}[0;34m"
 cc_normal=`echo -en "${esc}[m\017"`
+#}}}
 
 function contains() {
-local n=$#
-local value=${!n}
-for ((i=1;i < $#;i++)) {
-	if [ "${!i}" == "${value}"  ]; then
-		echo "y"
-		return 0
-	fi
+  #{{{
+  local n=$#
+  local value=${!n}
+  for ((i=1;i < $#;i++)) {
+    if [ "${!i}" == "${value}"  ]; then
+      echo "y"
+      return 0
+    fi
 
-}
-echo "n"
-return 1
-
+  }
+  echo "n"
+  return 1
+  #}}}
 }
 
 function createMakeFile(){
-      if [ "$GSL_BUILD_MODE" == "-release" ]; then 
-        ## detect if -release is used
-        ./configure.py --O3 $DEBUGMACROS $PLATFORM_OPTS
-      else
-        ./configure.py --O --debug $DEBUGMACROS $PLATFORM_OPTS
-      fi
+  #{{{
+    EXTRA_ARGS=${COLAB}
+    ## detect if -release is used for optimization and debugging options
+    if [ "$RELEASE" == "-release" ]; then
+      ## detect if building as NTS, MGS, or both
+      case $AS in
+          "-as-Nts") ./configure.py --O3 $PLATFORM_OPTS --as-Nts ${EXTRA_ARGS};;
+          "-as-Mgs") ./configure.py --O3 $PLATFORM_OPTS --as-Mgs ${EXTRA_ARGS};;
+          "-as-both-Nts-Mgs") ./configure.py --O3 $PLATFORM_OPTS --as-both-Nts-Mgs ${EXTRA_ARGS};;
+      esac
+    else
+      ## detect if building as NTS, MGS, or both
+      case $AS in
+          "-as-Nts") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-Nts ${EXTRA_ARGS};;
+          "-as-Mgs") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-Mgs ${EXTRA_ARGS};;
+          "-as-both-Nts-Mgs") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-both-Nts-Mgs ${EXTRA_ARGS};;
+      esac
+    fi
+  #}}}
 }
 
 SUPPORTED_PLATFORMS="LINUX BGL BGP BGQ SMP"
+
 #########################################
 #   PRINT HELP
 #{{{
 function print_help {
 	echo "SYNTAX: $0 
   -p <$SUPPORTED_PLATFORMS>    [default: LINUX]
-  [--clean | --rebuild | --remake]
-  -j <n>                  with <n> is num-processes [default: 2/3 total cores]
-  --release | <empty>   [default: (empty)]
-  -d 1                 [default: debug_assert]
-  -d 2                 [debug_hh] --> print debugs for Initialize() methods
-  -d 3                 [debug_in_loops] --> print debugs inside Loops
-  -d 4                 [debug_cpts] --> print compartmental information 
-     	--release: O3 with debug_assert
-     	--loglevel 1: debug with debug_assert and debug_hh for initialize methods
-     	--loglevel 2: debug with debug_assert and debug_hh and print out debug for loops
+  [--clean | --rebuild | --regen]
+  --regen               regenerate Makefile (gsl/Makefile)
+  -j <n>                with <n> is num-processes [default: 2/3 total cores]
+  -r|--release|<empty>  [default: (empty)]
+  -d 1                  [default: debug_assert]
+  -d 2                  [debug_hh] --> print debugs for Initialize() methods
+  -d 3                  [debug_in_loops] --> print debugs inside Loops
+  -d 4                  [debug_cpts] --> print compartmental information 
+
+  --gpu                 build/configure with GPU extensions
+  --arma                build/configure with Armadillo extensions
+
+  --release:            to build in release mode [default: debug mode]
+  --loglevel 1:         debug with debug_assert and debug_hh for initialize methods
+  --loglevel 2:         debug with debug_assert and debug_hh and print out debug for loops
+
+  --as-Nts:             build/configure as NTS
+  --as-Mgs:             build/configure as MGS
+  --as-both-Nts-Mgs:    build/configure as both NTS and MGS
+
+  --colab:              build/configure for colaborator's use
   "
 	echo "NOTE: [] (optional), <> (required)"
 	echo "NOTE: choose one value inside < >"
 	exit;
 }
 
-if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then 
+if [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$1" == "" ]; then 
   print_help
 fi
 #}}}
@@ -69,8 +97,13 @@ fi
 PLATFORM="LINUX"
 CLEAN=""
 REBUILD=""
-REMAKE=""
 GSL_BUILD_MODE=""
+RELEASE=""
+GPU=""
+ARMA=""
+AS="-as-Nts"
+COLAB=""
+REGENMAKEFILE=""
 DEBUGOPTS="1"
 NPROCS=$((`cat /proc/cpuinfo | grep processor | wc -l`))
 if [ "$#" -gt 2 ] ; then
@@ -92,7 +125,7 @@ while getopts "$optspec" optchar; do
       NPROCS=1
       ;;
     r) # release
-      GSL_BUILD_MODE="-release"
+      RELEASE="-release"
       ;;
     d) # log options
       DEBUGOPTS+=("$OPTARG")
@@ -105,15 +138,24 @@ while getopts "$optspec" optchar; do
           rebuild)
               REBUILD="-rebuild"
               ;;
-          remake)
-              REMAKE="-remake"
+          regen)
+              REGENMAKEFILE="-regen"
               ;;
           singlethread)
               NPROCS=1
               ;;
           release) # release
-            GSL_BUILD_MODE="-release"
-            ;;
+              RELEASE="-release"
+              ;;
+          gpu) # GPU extensions
+              GPU="-gpu"
+              ;;
+          arma) # Armadillo extensions
+              ARMA="-arma"
+              ;;
+          colab) # collaboration's use 
+              COLAB="--colab"
+              ;;
           loglevel=*)
             val=${OPTARG#*=}
             opt=${OPTARG%=$val}
@@ -130,6 +172,15 @@ while getopts "$optspec" optchar; do
                 ;;
             esac
             ;;
+          as-Nts) # as NTS
+              AS="-as-Nts"
+              ;;
+          as-Mgs) # as MGS
+              AS="-as-Mgs"
+              ;;
+          as-both-Nts-Mgs) # as both NTS and MGS
+              AS="-as-both-Nts-Mgs"
+              ;;
           someloglevel)
               val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
               echo "parsing option: '--${OPTARG}', value: '${val}'" >&2;
@@ -149,6 +200,7 @@ while getopts "$optspec" optchar; do
       echo "Invalid option: -$OPTARG" >&2
       exit 1
       ;;
+    # TODO: remove?
 #    :)
 #      echo "Option -$OPTARG requires an argument." >&2
 #      exit 1
@@ -179,6 +231,14 @@ case $PLATFORM in
     ;;
 esac
 
+if [ "$GPU" == "-gpu" ]; then
+    PLATFORM_OPTS+=" --with-gpu "
+fi
+
+if [ "$ARMA" == "-arma" ]; then
+    PLATFORM_OPTS+=" --with-arma "
+fi
+
 DEBUGMACROS="--debug_assert "
 for val in "${DEBUGOPTS[@]}"; do
   case $val in 
@@ -199,54 +259,71 @@ for val in "${DEBUGOPTS[@]}"; do
 done
 #}}}
 
-
-if [ "$CLEAN" == "-clean" ] || \
-   ( [ "$REBUILD" == "-rebuild" ] || \
-   [ "$REMAKE" == "-remake"  \
-   ] ) ; then 
-  if [ "$CLEAN" == "-clean" ] ; then
-    echo "clean-up GSL"
-    if [ -f Makefile ]; then 
-      make clean
-      rm Makefile
-    else
-      echo -e "${cc_red}No Makefile to clean ! ${cc_normal}\n";
-    fi
+CONTINUE=1
+if [ "$REGENMAKEFILE" == "-regen" ]; then 
+  #{{{
+  echo "Regen Makefile"
+  if [ -f Makefile ]; then 
+    rm Makefile
   fi
-  if [ "$REBUILD" == "-rebuild" ] || \
-    [ "$REMAKE" == "-remake" ] ; then 
-    if [ "$REMAKE" != "-remake" ]; then
-      echo "Rebuild GSL"
-      if [ ! -f Makefile ]; then
-        createMakeFile
+  # Generate Makefile and make!
+  createMakeFile
+  CONTINUE=0
+  #}}}
+fi 
+if [ $CONTINUE == 1 ]; then
+  if [ "$CLEAN" == "-clean" ] || \
+    [ "$REBUILD" == "-rebuild" ]; then \
+    if [ "$CLEAN" == "-clean" ] ; then
+      #{{{
+      echo "clean-up GSL"
+      if [ -f Makefile ]; then 
+        make clean
+        rm Makefile
+      else
+        echo -e "${cc_red}No Makefile to clean ! ${cc_normal}\n";
       fi
-      make clean
-      make -j $NPROCS;
-    else
+      #}}}
+    fi
+    if [ "$REBUILD" == "-rebuild" ]; then \
+      #{{{
+      echo "Rebuild GSL"
       if [ -f Makefile ]; then 
         rm Makefile
       fi
-      # Generate Makefile
+      # Generate Makefile and make!
       createMakeFile
-      echo "${cc_green}Recreate the Makefile only${cc_normal}"
+      make clean
+      if [ "$COLAB" == "--colab" ]; then 
+        make -j $NPROCS library
+      fi
+      make -j $NPROCS;
+      #}}}
     fi
-  fi
-else
+  else
 
-  if [ ! -f Makefile ]; then
-    createMakeFile
+    if [ ! -f Makefile ]; then
+      createMakeFile
+    fi
+    if [ "$COLAB" == "--colab" ]; then 
+      make -j $NPROCS library
+    fi
+    if [ $? -gt 0 ]; then
+      echo -e "${cc_red}Build GSL library failed ! ${cc_normal}\n";
+      exit 1;
+    fi
+    make -j $NPROCS;
   fi
-	make -j $NPROCS;
-fi
 
-if [ "$CLEAN" != "-clean" ] && { [ $? -gt 0 ] || [ ! `ls $LENSROOT/bin/gslparser` ];}; then 
-  echo -e "${cc_red}Build GSL failed ! ${cc_normal}\n";
-  exit; 
-elif [ "$CLEAN" == "-clean" ]; then 
-  echo -e "\n\n\n${cc_blue}You have removed GSL successful.${cc_normal}\n";
-  if [ "$REBUILD" == "-rebuild" ] && { [ `ls $LENSROOT/bin/gslparser` ];}; then 
+  if [ "$CLEAN" != "-clean" ] && { [ $? -gt 0 ] || [ ! `ls $LENSROOT/bin/gslparser` ];}; then 
+    echo -e "${cc_red}Build GSL failed ! ${cc_normal}\n";
+    exit 1;
+  elif [ "$CLEAN" == "-clean" ]; then 
+    echo -e "\n\n\n${cc_blue}You have removed GSL successful.${cc_normal}\n";
+    if [ "$REBUILD" == "-rebuild" ] && { [ `ls $LENSROOT/bin/gslparser` ];}; then 
+      echo -e "\n\n\n${cc_blue}Build GSL successful.${cc_normal}\n";
+    fi
+  else
     echo -e "\n\n\n${cc_blue}Build GSL successful.${cc_normal}\n";
   fi
-else
-  echo -e "\n\n\n${cc_blue}Build GSL successful.${cc_normal}\n";
 fi
