revise build: 1. using a single build_script file the build use models/all.mdf as the input (by default, so that the minimal build is used) - good for model evelopment for certain predefined system (e.g. NTS, NTSNVU, IBEx) the dedicated input file is models/nts.mdf models/ntsnvu.mdf, models/ibex.mdf to select such predefined system, we pass to build_script as --as-Nts, --as-Nts-NVU or --as-IBEx (check help message)
2. only packages that required are actually use for a given build

3. better detection + explaination about missing package(s)

diff --git a/gsl/build_gsl b/gsl/build_gsl
--- a/gsl/build_gsl
+++ b/gsl/build_gsl
@@ -31,22 +31,13 @@ function contains() {
 
 function createMakeFile(){
   #{{{
-    EXTRA_ARGS=${COLAB}
+    EXTRA_ARGS="${COLAB} ${BUILD_TARGET}"
     ## detect if -release is used for optimization and debugging options
     if [ "$RELEASE" == "-release" ]; then
       ## detect if building as NTS, MGS, or both
-      case $AS in
-          "-as-Nts") ./configure.py --O3 $PLATFORM_OPTS --as-Nts ${EXTRA_ARGS};;
-          "-as-Mgs") ./configure.py --O3 $PLATFORM_OPTS --as-Mgs ${EXTRA_ARGS};;
-          "-as-both-Nts-Mgs") ./configure.py --O3 $PLATFORM_OPTS --as-both-Nts-Mgs ${EXTRA_ARGS};;
-      esac
+      ./configure.py --O3 $PLATFORM_OPTS ${EXTRA_ARGS}
     else
-      ## detect if building as NTS, MGS, or both
-      case $AS in
-          "-as-Nts") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-Nts ${EXTRA_ARGS};;
-          "-as-Mgs") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-Mgs ${EXTRA_ARGS};;
-          "-as-both-Nts-Mgs") ./configure.py --Og --debug $DEBUGMACROS $PLATFORM_OPTS --as-both-Nts-Mgs ${EXTRA_ARGS};;
-      esac
+      ./configure.py --Og --debug ${DEBUGMACROS} $PLATFORM_OPTS ${EXTRA_ARGS}
     fi
   #}}}
 }
@@ -57,7 +48,7 @@ SUPPORTED_PLATFORMS="LINUX BGL BGP BGQ SMP"
 #   PRINT HELP
 #{{{
 function print_help {
-	echo "SYNTAX: $0 
+  echo "SYNTAX: $0 
   -p <$SUPPORTED_PLATFORMS>    [default: LINUX]
   [--clean | --rebuild | --regen]
   --regen               regenerate Makefile (gsl/Makefile)
@@ -75,15 +66,16 @@ function print_help {
   --loglevel 1:         debug with debug_assert and debug_hh for initialize methods
   --loglevel 2:         debug with debug_assert and debug_hh and print out debug for loops
 
-  --as-Nts:             build/configure as NTS
-  --as-Mgs:             build/configure as MGS
-  --as-both-Nts-Mgs:    build/configure as both NTS and MGS
+  PREDEFINED TARGETS:
+  --as-Nts              build NTS
+  --as-Nts-NVU          build NTS+NVU
+  --as-IBEx             build IBEx
 
-  --colab:              build/configure for colaborator's use
+  --colab:              build/configure shared libraries for colaborator's use
   "
-	echo "NOTE: [] (optional), <> (required)"
-	echo "NOTE: choose one value inside < >"
-	exit;
+  echo "NOTE: [] (optional), <> (required)"
+  echo "NOTE: choose one value inside < >"
+  exit;
 }
 
 if [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$1" == "" ]; then 
@@ -101,7 +93,7 @@ GSL_BUILD_MODE=""
 RELEASE=""
 GPU=""
 ARMA=""
-AS="-as-Nts"
+BUILD_TARGET=""
 COLAB=""
 REGENMAKEFILE=""
 DEBUGOPTS="1"
@@ -172,19 +164,23 @@ while getopts "$optspec" optchar; do
                 ;;
             esac
             ;;
-          as-Nts) # as NTS
-              AS="-as-Nts"
-              ;;
+          as-Nts)
+            BUILD_TARGET="--as-Nts"
+            ;;
+          as-Nts-NVU)
+            BUILD_TARGET="--as-Nts-NVU"
+            EXTRA_LIBS+=" USE_SUITESPARSE=1"
+            ;;
+          as-IBEx)
+            BUILD_TARGET="--as-IBEx"
+            ;;
           as-Mgs) # as MGS
-              AS="-as-Mgs"
-              ;;
-          as-both-Nts-Mgs) # as both NTS and MGS
-              AS="-as-both-Nts-Mgs"
-              ;;
+            BUILD_TARGET="-as-Mgs"
+            ;;
           someloglevel)
-              val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-              echo "parsing option: '--${OPTARG}', value: '${val}'" >&2;
-              ;;
+            val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
+            echo "parsing option: '--${OPTARG}', value: '${val}'" >&2;
+            ;;
           =*)
               val=${OPTARG#*=}
               opt=${OPTARG%=$val}
@@ -275,7 +271,7 @@ if [ $CONTINUE == 1 ]; then
       #{{{
       echo "clean-up GSL"
       if [ -f Makefile ]; then 
-        make clean
+        make clean ${EXTRA_LIBS}
         rm Makefile
       else
         echo -e "${cc_red}No Makefile to clean ! ${cc_normal}\n";
@@ -290,11 +286,11 @@ if [ $CONTINUE == 1 ]; then
     fi
     # Generate Makefile and make!
     createMakeFile
-    make clean
+    make clean ${EXTRA_LIBS}
     if [ "$COLAB" == "--colab" ]; then 
-      make -j $NPROCS library
+      make -j $NPROCS library ${EXTRA_LIBS}
     fi
-    make -j $NPROCS;
+    make -j $NPROCS ${EXTRA_LIBS};
     #}}}
   fi
 else
@@ -302,13 +298,13 @@ else
     createMakeFile
   fi
   if [ "$COLAB" == "--colab" ]; then 
-    make -j $NPROCS library
+    make -j $NPROCS library ${EXTRA_LIBS}
   fi
   if [ $? -gt 0 ]; then
     echo -e "${cc_red}Build GSL library failed ! ${cc_normal}\n";
     exit 1;
   fi
-  make -j $NPROCS;
+  make -j $NPROCS ${EXTRA_LIBS};
 fi
 
 if [ "$CLEAN" != "-clean" ] && { [ $? -gt 0 ] || [ ! `ls $LENSROOT/bin/gslparser` ];}; then 
diff --git a/models/define b/models/define
--- a/models/define
+++ b/models/define
@@ -22,8 +22,8 @@ function run_mdlparser() {
   # NOTE: $LENSROOT/extensions/functor need to be added explicitly to configure.py
   #temp_mdf_only=$(mktemp)
   #temp_mdl_only=$(mktemp)
-  #grep  '^[^//]' $1 | awk '/mdf"/ {print $2}' > ${temp_mdf_only}
-  #grep  '^[^//]' $1 | awk '/mdl"/ {print}' > ${temp_mdl_only}
+  #grep  '^[^//]' $1 | gawk '/mdf"/ {print $2}' > ${temp_mdf_only}
+  #grep  '^[^//]' $1 | gawk '/mdl"/ {print}' > ${temp_mdl_only}
   $MDLROOT/bin/mdlparser $1 -i $LENSROOT/extensions/variable:$LENSROOT/extensions/struct;
   #$MDLROOT/bin/mdlparser `cat ${temp_mdf_only} | tr '\n' ' ' ` ${temp_mdfl_only} -i $LENSROOT/extensions/variable:$LENSROOT/extensions/struct;
   #}}}
@@ -32,23 +32,23 @@ function run_mdlparser() {
 
 temp_mdf_only=$(mktemp)
 temp_mdl_only=$(mktemp)
-grep  '^[^//]' $1 | awk '/mdf"/ {print}' > ${temp_mdf_only}
-grep  '^[^//]' $1 | awk '/mdl"/ {print}' > ${temp_mdl_only}
+grep  '^[^//]' $1 | gawk '/mdf"/ {print}' > ${temp_mdf_only}
+grep  '^[^//]' $1 | gawk '/mdl"/ {print}' > ${temp_mdl_only}
 
 MDLFILES=()
 sed '/\\/p' ${temp_mdl_only}| sed 's/#include "/cd /g' | sed 's/\(.*\)\//\1 ; $MDLROOT\/bin\/mdlparser /g' | sed 's/"/ ; sh copyModules ; cd - ;/g' > defineModels1.sh;
 while read mdl_in; do 
-  mdl_file_name=`echo $mdl_in | awk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
+  mdl_file_name=`echo $mdl_in | gawk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
   MDLFILES+=($mdl_file_name)
 done < $temp_mdl_only
 while read in; do 
-  file_name=`echo $in | awk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
+  file_name=`echo $in | gawk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
   if [ -f $file_name ]; then
     cat ${file_name} | grep  '^[^//]'  | sed '/\\/p' | sed 's/#include "/cd /g' | sed 's/\(.*\)\//\1 ; $MDLROOT\/bin\/mdlparser /g' | sed 's/"/ ; sh copyModules ; cd - ;/g' >> defineModels1.sh;
     temp_file_name=$(mktemp)
-    grep  '^[^//]' $1 | awk '/mdl"/ {print}' > ${temp_file_name}
+    grep  '^[^//]' $1 | gawk '/mdl"/ {print}' > ${temp_file_name}
     while read mdl_in; do 
-      mdl_file_name=`echo $mdl_in | awk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
+      mdl_file_name=`echo $mdl_in | gawk  '{print \$2}' | sed -e "s/^\"//" -e "s/\"$//"  `
       MDLFILES+=($mdl_file_name)
     done < $temp_file_name
   fi
@@ -56,10 +56,10 @@ done < ${temp_mdf_only}
 
 RERUN=0
 if [ $# -gt 1 ] && [ $2 == "-rebuild" ]; then
-  awk '{ print  $0 }' defineModels1.sh > defineModels2.sh;
+  gawk '{ print  $0 }' defineModels1.sh > defineModels2.sh;
   RERUN=1
 else
-  awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; for i in \$(awk -F\" |{\"  '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk -F\" |{\" '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Constant\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk -F\" |{\" '"'"'{if (\$1==\"Variable\" ) {print \$(2);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(comm -12 <(cpp " $2 "/" $5 "|awk -F\" |{\" '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"'|sort) <(awk -F\" |{\" '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"' " $2 "/" $5 "|sort)); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; if ! cmp --silent <(cpp " $2 "/" $5")   " $2 "/." $5 "; then cpp " $2 "/" $5 " >" $2 "/." $5 ";" $0 " fi" }' defineModels1.sh > defineModels2.sh;
+  gawk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; for i in \$(gawk -F\" |{\"  '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(gawk -F\" |{\" '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Constant\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(gawk -F\" |{\" '"'"'{if (\$1==\"Variable\" ) {print \$(2);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(comm -12 <(cpp " $2 "/" $5 "|gawk -F\" |{\" '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"'|sort) <(gawk -F\" |{\" '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"' " $2 "/" $5 "|sort)); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; if ! cmp --silent <(cpp " $2 "/" $5")   " $2 "/." $5 "; then cpp " $2 "/" $5 " >" $2 "/." $5 ";" $0 " fi" }' defineModels1.sh > defineModels2.sh;
 fi
 
 set -e
@@ -90,15 +90,3 @@ cp $LENSROOT/Extensions.mk{,.bak}
 cp Extensions.mk $LENSROOT
 rm ${temp_mdf_only}
 rm ${temp_mdl_only}
-
-# <<<OLD_MGS; uncomment these
-#touch define;
-#touch $1;
-#    OLD_MGS>>>
-
-#grep  '^[^//]' $1 | sed '/\\/p' | sed 's/#include "/cd /g' | sed 's/\(.*\)\//\1 ; $MDLROOT\/bin\/mdlparser /g' | sed 's/"/ ; sh copyModules ; cd - ;/g' > defineModels1.sh;
-  #awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi" }' defineModels1.sh > defineModels2.sh;
-  #awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; if [ ! -d " $2 "/`awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1); exit;}}'"'"' " $2 "/" $5 "` ]; then " $0 " fi " }' defineModels1.sh > defineModels2.sh;
-  #awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; for i in \$(awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done " }' defineModels1.sh > defineModels2.sh;
-  #awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; for i in \$(awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Constant\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk '"'"'{if (\$1==\"Variable\" ) {print \$(2);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done " }' defineModels1.sh > defineModels2.sh;
-  #awk 'NF { print "if [ ! -f " $2 "/" $5" ]; then echo \" not found: " $2 "/" $5 "\"; exit 1; fi; if [ '$1' -ot " $2 "/" $5 " ] || { [ define -ot '$1' ] && [ define -ot " $2 "/" $5 " ];}; then " $0 " fi; for i in \$(awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Node\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk '"'"'{for(i=1;i<=NF;i++) if (\$i==\"Constant\" && \$(i+2)==\"Implements\") {print \$(i+1);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(awk '"'"'{if (\$1==\"Variable\" ) {print \$(2);}}'"'"' " $2 "/" $5 "); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done; for i in \$(comm -12 <(cpp " $2 "/" $5 "|awk '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"'|sort) <(awk '"'"'{if (\$1==\"Interface\" ) {print \$(2);}}'"'"' " $2 "/" $5 "|sort)); do if [ ! -d " $2 "/$i ]; then " $0 " fi; done " }' defineModels1.sh > defineModels2.sh;
